name: anime_dart
description: "Um App para Android para assistir animes ou fazer download de episódios. Com features de procurar, favoritos, lançamentos, populares e mais."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  outline_material_icons: ^0.1.1
  http: ^0.13.5
  cached_network_image: ^2.2.0+1
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  get_it: ^4.0.4
  video_player: ">=0.10.11+2 <2.0.0"
  shared_preferences: ^0.5.8
  diacritic: ^0.1.1
  url_launcher: ^5.5.0
  mockito: ^5.3.2
  dartz: ^0.9.1
  string_validator: ^0.1.4
  dio: ^5.0.3
  hive: ^2.2.3
  path_provider: ^1.6.24
  flick_video_player: ^0.1.1
  file_picker: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/waifu.png
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  coverage: flutter test --coverage & remove_from_coverage -f coverage/lcov.info -r .g.dart$
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
